

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./utils -components/header-footer/Navigation";
import Footer from "./utils -components/header-footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }:{ children: React.ReactNode}) {
  return (
    <html lang="en">

      <body className={inter.className}>{children}</body>

    </html>
  );
}
